### ISSUE TITLE
Add Vivaldi to supported browsers

### ISSUE THREAD

**Issue by danielnieto** [jkroso/atom-browser-refresh-on-save#6]
Hello, I've switched to Vivaldi as my main browser and I'd like to have the live refresh feature on it, since Vivaldi is Chromium plus some stuff I'm guessing it should work the same as Chrome, can you point me out to which file should I look into/modify to have vivaldi working with Refresh on save? Thank you a lot.

**Comment by jkroso** [comment]
Well if it will respond to applescript the its just a matter of adding the applescript command [here](https://github.com/jkroso/atom-browser-refresh-on-save/blob/7dfeee58067fd149467e6689faf6bb1bd2002412/plugin.coffee#L78-L83) and adding a line to the main function [here](https://github.com/jkroso/atom-browser-refresh-on-save/blob/7dfeee58067fd149467e6689faf6bb1bd2002412/plugin.coffee#L98-L99). Otherwise it will be a bit harder
